### ISSUE TITLE
textures do not properly update when cells are clicked

### ISSUE THREAD

**Issue by Errorcrafter** [BalaM314/Einsteinium#1]
when clicking on an empty cell, it shows the water cooler texture, which (after looking through inspect element) is item id 2. however, clicking the water cooler does not update its texture to whatever item id 1 or 3 is.

video: (yes its fucking sharex deal with it)

https://g1ga.is-a-skid.wtf/041c79d.mp4

**Comment by BalaM314** [comment]
![image](https://user-images.githubusercontent.com/71201189/126092105-611997f3-40c0-4b50-a93c-9ed83ee81a3c.png)
🤷
For me it works fine, please provide the video in a format that I can view.

**Comment by Errorcrafter** [comment]
its literally an mp4

**Comment by BalaM314** [comment]
This is expected behavior.
Sorry you didnt notice the input at the bottom to change the block you're placing, I should make it more clear(but this is alpha).
